---
- hosts: all

  tasks:
    - name: Copy sensu repo file to /etc/repos
      ansible.buildin.file:
        src: sensu_stable.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
    
    - name: Install sensu-go-agent
      ansible.buildin.yum:
        name: sensu-agent
        state: installed
    
    - name: Copy agent.yml file
      ansible.buildin.file:
        src: agent.yml
        dest: /etc/sensu/
        owner: root
        group: root
    
    - name: restart sensu service
      ansible.buildin.service:
        name: sensu-agent
        state: restarted
        enabled: yes
