---
- hosts: all

  tasks:
      
    - name: restart sensu service
      service:
        name: nginx
        state: restarted
        enabled: yes
      register: servicestatus
      unitl: servicestatus.status.ActiveState == "active"
      retries: 15
      delay: 30
